#!/bin/bash

# Array com as frases do Homem-Aranha
frases=(
"Com grandes poderes, vêm grandes responsabilidades."
"Sou o seu amigão da vizinhança, Homem-Aranha!"
"O que fazemos define quem somos."
"Às vezes, perder a pessoa que amamos nos ajuda a encontrar o propósito que estávamos buscando."
"Não sou nada sem o meu traje? Se isso é verdade, eu não deveria tê-lo."
"Se o mundo te diz que você não é nada sem a máscara, então você nunca deveria usá-la."
"E quem disse que isso é problema meu?!"
"Eu só sou o Homem-Aranha porque o mundo precisa que eu seja."
"Todos têm seus próprios problemas. A vida é uma luta constante."
"O verdadeiro poder não vem de nossas habilidades, mas de nossas escolhas."
"Se você guardar muita raiva dentro de você, ela acabará te consumindo."
"Às vezes, ser o herói significa fazer sacrifícios que os outros não entenderão."
"Nunca é tarde para fazer a coisa certa."
"Eu caio, mas sempre me levanto."
"Eu luto porque ninguém mais pode."
"O que importa não é o que perdemos, mas o que escolhemos fazer com o que resta."
"Eu sou o Homem-Aranha... porque não posso deixar de ser."
"Eu sou apenas um garoto tentando fazer a coisa certa."
"Não podemos salvar a todos, mas isso não significa que não devemos tentar."
"O crime nunca dorme, e eu também não."
"Cada escolha que fazemos define o tipo de pessoa que seremos."
"A responsabilidade de ser um herói pesa mais do que qualquer vilão."
"Às vezes, ser um herói significa aceitar que você não pode ganhar todas as batalhas."
"Eu não faço isso pelo reconhecimento. Faço porque é o certo."
"Eu sempre vou me levantar, não importa quantas vezes eu caia."
"O medo é um inimigo poderoso, mas nunca deixo que ele me controle."
"Ser herói não é sobre poder, é sobre coragem."
"Eu sou mais do que apenas a máscara."
"O mundo precisa de heróis, mesmo que eles sejam imperfeitos."
"A justiça não é algo fácil, mas é sempre necessária."
"Sempre haverá escuridão, mas eu sou a luz que luta contra ela."
"Não importa o quão forte seja o inimigo, eu nunca vou desistir."
"Se eu puder salvar apenas uma pessoa, todo sacrifício vale a pena."
"Todo mundo merece uma segunda chance."
"Os verdadeiros heróis não são aqueles que nunca erram, mas os que continuam tentando."
"Eu uso a máscara para proteger aqueles que amo."
"A vida é cheia de desafios, mas sou mais forte do que qualquer obstáculo."
"Ser herói significa estar disposto a perder tudo para proteger os outros."
"Eu aprendi que o sacrifício faz parte de ser o Homem-Aranha."
"O passado pode doer, mas não podemos deixar que ele defina quem somos."
"Eu caí tantas vezes, mas isso só me fez mais forte."
"Todo mundo tem medo, até heróis. A diferença é que nós enfrentamos o medo."
"Não sou o herói que o mundo quer, mas sou o herói que ele precisa."
"Cada pessoa que ajudo é uma vitória contra a escuridão."
"Não importa o quanto tentem me derrubar, eu sempre me levanto."
"Heróis de verdade não lutam por fama ou glória, lutam por justiça."
"Todos temos cicatrizes, mas elas não definem quem somos."
"A vida sempre nos desafia, mas nunca devemos desistir."
"Ser um herói é tomar decisões difíceis, mas necessárias."
"As pessoas precisam de esperança, e é isso que tento dar."
"Eu poderia desistir, mas isso não seria quem eu sou."
"Nunca subestime o poder da determinação."
"Às vezes, tudo o que podemos fazer é seguir em frente."
"A cidade precisa de mim, e eu nunca vou decepcioná-la."
"A verdadeira força vem de dentro, não dos músculos."
"Eu luto por aqueles que não podem lutar por si mesmos."
"Ser herói significa fazer o impossível, todos os dias."
"Eu não sou perfeito, mas faço o meu melhor."
"Eu continuo lutando, mesmo quando tudo parece perdido."
"Cada batalha é uma chance de provar o meu valor."
"O poder sem responsabilidade é o caminho para a ruína."
"Sei que não posso salvar todos, mas nunca vou parar de tentar."
"O verdadeiro herói não busca reconhecimento, apenas faz o que é certo."
"Eu luto por um amanhã melhor, não importa o quanto o presente seja sombrio."
"O medo de falhar não vai me parar."
"Eu poderia ser qualquer coisa, mas escolhi ser o Homem-Aranha."
"Às vezes, tudo o que temos é esperança — e isso é suficiente."
"Todo erro que cometo me ensina algo novo."
"Eu sou um símbolo, não só um homem."
"Com o tempo, aprendi que nem todo inimigo usa uma máscara."
"Cada novo dia é uma chance de fazer a diferença."
"A dor nos fortalece, nos molda."
"Ser um herói é mais do que ter poderes; é ter coração."
"Mesmo que ninguém veja, cada ação conta."
"Eu sou o herói de hoje, mas outros virão amanhã."
"Nunca subestime a coragem de um homem com algo a perder."
"Eu protejo os inocentes porque ninguém mais o fará."
"O sacrifício é parte da vida de um herói."
"Eu sou quem sou por causa das escolhas que fiz."
"Às vezes, o herói também precisa de ajuda."
"Eu continuo lutando, não porque é fácil, mas porque é o certo."
"Cada herói precisa de um propósito, e o meu é proteger."
"A justiça não dorme, e eu também não."
"Eu não sou apenas o Homem-Aranha. Eu sou Peter Parker também."
"Minha maior arma não é minha teia, é minha determinação."
"Ser herói é um fardo que eu escolhi carregar."
"Eu vivo para lutar outro dia, porque a luta nunca termina."
"Heróis também cometem erros, mas nunca deixam de aprender."
"Eu não estou sozinho. Sempre há pessoas que acreditam em mim."
"Eu caí inúmeras vezes, mas sempre me levantei."
"Meu legado não será definido pelo número de vitórias, mas pelo número de pessoas que ajudei."
"O verdadeiro poder de um herói vem de sua capacidade de inspirar os outros."
"O peso da responsabilidade nunca me abandonará, e eu aceito isso."
"Cada inimigo derrotado é uma lição aprendida."
"Meu maior inimigo é a dúvida, mas eu nunca deixo ela vencer."
"Um herói nunca desiste, mesmo quando está sozinho."
"A verdadeira vitória é proteger aqueles que não podem se proteger."
"Eu sou o Homem-Aranha porque preciso ser, não porque quero."
"O que nos define não são os poderes, mas as decisões que tomamos."
"Ser herói significa sempre buscar ser melhor."
"A teia que tecemos em nossas vidas nos conecta a todos."
)

# Gera um número aleatório entre 0 e o número de frases - 1
indice=$((RANDOM % ${#frases[@]}))

# Exibe a frase correspondente ao índice gerado
echo "
${frases[$indice]}
"

